version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.12.1
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g pnpm"
      - restore_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install Dependencies
          command: pnpm i
      - save_cache:
          key: dependency-cache-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: pnpm run lint
      - run:
          name: build
          command: pnpm run build
